### ISSUE TITLE
 /user/100  match  p.Get("/user/:id"

### ISSUE THREAD

**Issue by tablecell** [go-playground/pure#13]
```
package main

import (
	"net/http"

	"github.com/go-playground/pure/v5"
	mw "github.com/go-playground/pure/v5/_examples/middleware/logging-recovery"
)

func main() {

	p := pure.New()
	p.Use(mw.LoggingAndRecovery(true))

	p.Get("/user/:id", helloWorld)

	http.ListenAndServe(":3007", p.Serve())
}

func helloWorld(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Hello World"))
}
```
http://localhost:3007/user/    404
http://localhost:3007/user/100  right
http://localhost:3007/user/100/  expect 404 but result same as  /user/100

**Comment by deankarn** [comment]
@tablecell pure sets a series of sane defaults upon creation which includes redirecting upon a non-matching trailing slash.

If you use curl -v ... you should see the redirect request. This can be turned off if desired.
