### ISSUE TITLE
static file syntax

### ISSUE THREAD

**Issue by nkev** [go-playground/pure#4]
I have a root folder /static with subfolders for js, css, etc. The code:

```Go
p.Get("/static/*", http.FileServer(http.Dir("static/")).ServeHTTP)
```
...gives me a 404 in the browser even though the paths in the browser are correct (e.g. http://localhost:5000/js/plugins/prism.js)

I would like the URL in the browser to remain `http://localhost:5000/js/plugins/prism.js` 
What should the code look like?

**Comment by joeybloggs** [comment]
@nkev the only way to make that work would be to bring the folders in the static directory up to the root and add a handler for each folder just like the static folder; I don't recommend this approach though.

I suppose you could also keep the folders in the static dir and add individual handlers for each inner folder and the SkipPrefix you would also have to add the inner.

Something like
p.Get("/js/*", http.StripPrefix("static/js/", http.FileServer(http.Dir("static"))).ServeHTTP)
Responding from my phone so havented tested, but something like that should work
