### ISSUE TITLE
Can middleware share info?

### ISSUE THREAD

**Issue by nkev** [go-playground/pure#6]
Hi Dean,

How would a middleware function (e.g. JWT auth) share data (a JWT struct) to all the remaining middleware functions in the chain? `RequestVars` seems to be read-only.

**Comment by joeybloggs** [comment]
@nkev yes

It is intended, and how I pass RequestVars down, by using context.Context on the http.Request.
For details please see https://golang.org/pkg/net/http/#Request.WithContext

Please let me know if that helps or if more clarity is needed :)

**Comment by nkev** [comment]
Thanks, so how would you pass a JWT struct from one middleware to te next?

**Comment by harnash** [comment]
@nkev 
Something like this should work:
```go
type key int
const jwtIdKey key = 123

func JWT(jwt *JWTStruct) pure.Middleware {
	fn := func(next http.HandlerFunc) http.HandlerFunc {
             return func(w http.ResponseWriter, r *http.Request) {
                 next(w, r.WithContext(context.WithValue(r.Context(), jwtIdKey, jwt)))
             }
        }
}
```
Now you need to be careful about the order that you register your middlewares in to make sure JWT middleware is invoked before other that relies on it.
