### ISSUE TITLE
_examples/ vs examples/

### ISSUE THREAD

**Issue by powerman** [go-playground/pure#7]
Some your other packages (in other repos) try to import using `examples/` path instead of `_examples/` - this breaks things like `go install all` which process all packages, including ones in examples directories.

**Comment by joeybloggs** [comment]
Please let me know which other repos and I'll try and get that fixed this weekend

**Comment by powerman** [comment]
I didn't included the list because I believe it's easier for you to grep your repos… anyway, here it is (there may be others - I didn't checked _all_ your repos):
https://github.com/go-playground/universal-translator/blob/master/examples/full-with-files/main.go#L15
https://github.com/go-playground/universal-translator/blob/master/examples/full-no-files/main.go#L15

**Comment by joeybloggs** [comment]
Thanks
